version: '3.1'

services:
  app:
    image: 'nosql'
    ports:
      - "9090:9090"
    build:
      context: .
    container_name: app
    depends_on:
      - PostgreSQL
      - mongodb

  PostgreSQL:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=words

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    hostname: mongo
