version: '3.1'

services:
  app:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    image: 'app.jar'
    ports:
      - "9090:9090"
    build: .
    container_name: app
    networks:
      network_all: { }
    depends_on:
      - postgresql
      - mongodb

  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql
    hostname: postgresql
    networks:
      network_all: { }
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - "./src/main/resources/postgres/script:/docker-entrypoint-initdb.d"
      - "postgres-volume:/var/lib/postgresql/data"

  adminer:
    image: adminer
    ports:
      - 8020:8080
    networks:
      network_all: { }

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    networks:
      network_all: { }
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
      - "./src/main/resources/mongo/script/init.js:/docker-entrypoint-initdb.d/init.js"
volumes:
  mongodb-data:
  postgres-volume:

networks:
  network_all: { }
